### PR TITLE
All in one

### PR DESCRIPTION
**Pull request by pronan**
Sorry, chun ge. A new PR again. My brain's in a big mess when studying `git cherry-pick`. I expect it is used like `git cherry-pick openresty/opm/master pronan/opm/master`. Now this PR contains both `README.md` and `opm` changes needed. Shall we work on this PR and close #22 and #26?

### CODE REVIEW

**Comment by agentzh** [comment]
@pronan The diffs in this PR look wrong. Please check it out yourself:

https://github.com/openresty/opm/pull/27/files

Seems like your branch is based on an older master that is out of date.

**Comment by agentzh** [comment]
@pronan BTW, you should really spend some time studying git usage. For example, you should put the commit ID as the argument to the `git cherry-pick` command.

**Comment by pronan** [comment]
@agentzh hello chunge, I've checked again. This time I copy the whole content of `README.md` and `opm` of your current master branch to mine first, and then add my changes, then commit. Finally I find only `README.md` changes and have conflicts. It should be OK this time.

**Comment by agentzh** [comment]
@pronan Your branch is messed up. Please start over by branching the latest master branch of the official repo.

**Comment by agentzh** [comment]
@pronan Otherwise, I can not merge your changes since they lead to conflicts.

**Comment by agentzh** [comment]
@pronan You should really familiarize yourself with the git command line usage to save your time (and my time as well) :)

**Comment by agentzh** [comment]
@pronan To update your local master branch from the remote. You need to add the official repo to your remotes and merge from that remote (instead of your own fork's remote). Alas, I don't think I should teach git usage here :)) You can find a lot of tutorials on the web.

**Comment by pronan** [comment]
@agentzh Hello, chun ge. Sorry for that. I've tried to read some tutorial on line like [this](http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request) but still confused. Looks like I can't do this in a short term. It seems that Github PR is always triggered by edit a single file and after that you either commit it to make a PR or get refused, no place to edit another file.

Could we just go with one PR one file this time (namely #22 and #26)?  Also you can copy these code changes to your master branch and commit directly and simply close my PRs. I won't make a PR that requires two or more files changes until I know how to do it.

**Comment by agentzh** [comment]
@pronan As I've said, you should really use the command-line interface of git for changes. Using GitHub's web UI to do edits and PRs surely sucks.

**Comment by agentzh** [comment]
This PR is corrupted. I'm closing it.

**Pull request closed without merging**
